# redis server up
# $> docker-compose -f {file name} up -d 

# redis cli access
# $> docker exec -it -{docker id or name} redis-cli

# redis keys 검색
# $> keys * <= 전체 등록되 키 다 나옴
# $> GET "{검색된 key}"


version: '3.7'
services:
    redis:
      image: redis:alpine
      command: redis-server --port 6379
      container_name: redis_boot
      hostname: redis_boot
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - 6379:6379
