---
development:
  dialect: postgres
  database: mc_web_console_api_development

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/mc_web_console_api_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/mc_web_console_api_production?sslmode=disable"}}
