import { defineConfig, devices } from '@playwright/test';
import { defineBddConfig } from 'playwright-bdd';
import { config } from './fixtures/test-data';
import { humanSlowMoMs } from './support/humanize';

/**
 * Generates Playwright tests by mapping Korean .feature files (features/) to steps (steps/).
 * Run: `npm run test:e2e` (= bddgen && playwright test)
 */
const testDir = defineBddConfig({
  features: 'features/**/*.feature',
  steps: 'steps/**/*.ts',
  // Tell the generated spec to use the custom test (the auto mock fixture in support/fixtures.ts).
  // Without this, the spec imports the base playwright-bdd test and the @unit mock isn't installed.
  importTestFrom: 'support/fixtures.ts',
});

/**
 * ★ @costly — tests that actually create or delete cloud resources (which incur charges).
 *   Excluded by default; only run when E2E_INCLUDE_COSTLY=1.
 *   (Until now this gate wasn't in the config at all, so destructive tests like infra
 *   deletion were running every time.)
 */
const includeCostly = process.env.E2E_INCLUDE_COSTLY === '1';

/**
 * ★ Evidence retention (on by default, disable with `E2E_EVIDENCE=0`)
 *
 * A single "PASS" line doesn't let a person confirm it really worked. Even if the screen
 * is empty or the wrong data is shown, it looks like PASS as long as the assertions pass.
 * So *even for passing tests* we keep the start screen, end screen, and video, so a person
 * can judge with their own eyes.
 *
 *  - screenshot 'on'  : capture a screen per test (+ fixtures attach before/after separately)
 *  - video 'on'       : video of the whole test — records exactly what was shown at each step
 *  - trace 'on'       : lets you retrace the DOM and network at each action
 *
 * Results land in `playwright-report/` (HTML) and `test-results/`, grouped per test in the HTML report.
 * If the size is a burden in CI, reduce with E2E_EVIDENCE=0 to keep only failures.
 */
const evidence = process.env.E2E_EVIDENCE !== '0';

export default defineConfig({
  testDir,
  // Fix a RUN_ID at startup so all worker processes use the same resource names (support/naming.ts).
  globalSetup: './support/globalSetup.ts',
  fullyParallel: false,
  // @unit/@scenario share the real lineup state, so run serially (parallel would cause data collisions).
  workers: 1,
  timeout: 90_000,
  expect: { timeout: 15_000 },
  reporter: [
    ['list'],
    ['html', { open: 'never', outputFolder: 'playwright-report' }],
    // ★ Per-scenario summary report — generated by default, not created if E2E_SUMMARY_REPORT=0.
    //   Where the default HTML report is for *drilling into failures*, this is for scanning
    //   "what scenarios exist, whether each passed, and how the screen looked" at a glance
    //   (print it as-is and it's a PDF report).
    ['./support/summaryReporter.ts'],
  ],
  use: {
    baseURL: config.baseURL,
    actionTimeout: 15_000,
    navigationTimeout: 30_000,
    // ★ Human pacing (demo visibility) — a slowMo baseline on every low-level action, on ONLY when
    //   E2E_HUMAN_PACE=1 (0 otherwise, so CI is unaffected). The per-step hover/hold beats are added
    //   on top of this by support/humanize.ts at the scenario page-object interaction points.
    launchOptions: { slowMo: humanSlowMoMs() },
    screenshot: evidence ? 'on' : 'only-on-failure',
    trace: evidence ? 'on' : 'retain-on-failure',
    video: evidence ? 'on' : 'retain-on-failure',
    ignoreHTTPSErrors: true,
  },

  /**
   * ★ Three-tier structure — structurally eliminates "failed because there's no data" in functional tests.
   *
   *     seed ─┬─→ functional
   *           └─→ scenario
   *
   * @unit functional tests hit the real lineup without a mock (the point is to catch contract
   * changes in the connected frameworks). So the source model, target model, and workflow must
   * *actually exist*. But nobody was creating that data, so tests were dying on timeout waiting
   * for names like e2e-nano-source.
   *
   * The seed project runs first and creates that data (real source-server collection → source/
   * custom/target models → charge-safe workflow), and functional/scenario run on top of it.
   * The order is *made explicit* via Playwright's project dependencies — we don't rely on
   * implicit ordering like filename sorting.
   */
  projects: [
    {
      name: 'seed',
      use: { ...devices['Desktop Chrome'] },
      grep: /@seed/,
      // Real source-server collection and recommendation are involved, so 90s isn't enough.
      timeout: 15 * 60_000,
    },
    {
      name: 'functional',
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['seed'],
      grep: /@unit/,
      grepInvert: includeCostly ? undefined : /@costly/,
    },
    {
      // Notification badge checks (@notify) run hermetically with @mock — they only look at how
      // our tracker turns a run result into a badge, so they need neither seed (real source
      // collection) nor cloud resources. So unlike functional, they get an independent lane that
      // doesn't depend on seed (only login goes out to the real backend).
      name: 'notify',
      use: { ...devices['Desktop Chrome'] },
      grep: /@notify/,
    },
    {
      // Notification badge real-data check (@live) — without a mock, verifies through real
      // execution and real notifications. It uses only charge-safe examples so it creates no
      // cloud resources, but waits generously until the real run finishes.
      name: 'live',
      use: { ...devices['Desktop Chrome'] },
      grep: /@live/,
      timeout: 8 * 60_000,
    },
    {
      name: 'scenario',
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['seed'],
      grep: /@scenario/,
      // Scenarios actually create EC2 (@costly). Excluded from the default run; only run when E2E_INCLUDE_COSTLY=1.
      grepInvert: includeCostly ? undefined : /@costly/,
      // One scenario spans workflow run → cm-beetle migration → EC2 creation → nginx install → load test.
      // Allow plenty of time since the cloud is actually provisioning resources.
      timeout: 60 * 60_000,
    },
  ],
});
