---
development:
  url: {{envOr "DEV_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/api_dev?sslmode=disable"}}

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/api_test?sslmode=disable"}}

production:
  url: {{envOr "PROD_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/api_production?sslmode=disable"}}
