name: CM-Butterfly CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build-source:
    name: Build CM-Butterfly source code
    strategy:
      matrix:
        go-version: ["1.19"]
        os: [ubuntu-22.04]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
          go-version: ${{matrix.go-version}}

    - name: Build binary executable file
      run: go build -v -o cm-butterfly main.go

 
  build-container-image:
    name: Build a cm-butterfly container image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build
        env:
          IMAGE_NAME: ${{ github.event.repository.name }}
        run: docker build . --file Dockerfile --tag $IMAGE_NAME